### ISSUE TITLE
Add rotation to camera at waypoints?

### ISSUE THREAD

**Issue by janithajc** [IllusionBox/Light-Beam-Pee-Alpa#7]
When the camera reaches a _waypoint_, so far the script handles **wait for seconds** and **speed from that waypoint**. I can also add **rotate by angle** to make the game more _immersive_ but don't know if it will.
**Quicker the _response_, quicker the _progress_**

**Comment by maleenj** [comment]
It doesnt necessarily need to curve...that would be complicated to make noh? For now lets have it move linearly and make the track not take any sudden curves. If it looks bad we can try curving. Btw have you checked out Unity's navigation system and the use of NavMeshes video I sent you? 

http://unity3d.com/learn/tutorials/topics/navigation

Seems like you can easily define paths according to something called nav meshes. Curves or otherwise.

**Comment by maleenj** [comment]
http://answers.unity3d.com/questions/902933/navmesh-vs-waypoint-network-ai-best-practices.html

Quote:

"This is probably for the forums, but a navmesh is pretty much always a lot better than a waypoint network.
You'll use the same algoritm (A*) for pathfinding through a navmesh and through waypoints, but with waypoints you either have a lot more corners, or be a lot less accurate than the navmesh solution.
It's also easier to make movement look good with a navmesh - there's a ton of different curves (like bezier) that you can make based on the navmesh corners that'll stay inside the mesh. You can't do that with waypoints.
Oh, and speaking from experience - going from a waypoint system with 1 meter between the points to the built in navmesh cut the time it took to pathfind down to 1/100th of what it was. use a navmesh."

**Comment by janithajc** [comment]
Awez! I think the conversation we had today closes this.

**Comment by maleenj** [comment]
YupZ :D
